### ISSUE TITLE
Changelog failed in recent PR

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#1495]
#1493 provided the changelog_entry.yaml correctly, but the [action failed](https://github.com/PolicyEngine/policyengine-us/actions/runs/3462937816)

**Comment by martinholmer** [comment]
@nikhilwoodruff,  Thank for fixing issue #1495.   Now there is no merge conflict in PR #1494.

**Comment by martinholmer** [comment]
@nikhilwoodruff,  I spoke too soon.   The merge conflict in PR #1494 is gone, so the tests run.  But the check version number test fails.   Here are the details:

<img width="1302" alt="Screen Shot 2022-11-14 at 4 35 27 PM" src="https://user-images.githubusercontent.com/12170745/201770890-358652a1-3710-4abc-9f1e-b35ac56ee1e9.png">

**Comment by nikhilwoodruff** [comment]
Ah thanks for noticing @martinholmer! That's odd, I thought I got the issue but maybe there's a missing tag now. Will take a look by tomorrow.

**Comment by nikhilwoodruff** [comment]
OK it seems like it was fixed by `git pull`ing `master` into your PR.

**Comment by martinholmer** [comment]
@nikhilwoodruff said:
> OK it seems like it was fixed by `git pull`ing `master` into your PR.

Thanks.  So are you saying that **every time** I submit a pull request, I need to do the
`git pull master` command before doing `git push origin BRANCHNAME`?

If so, should the command be `git pull origin master`  or  `git pull upstream master`?

**Comment by nikhilwoodruff** [comment]
@martinholmer actually I don't think we have to here! I think this is fixed now, though there's one specific circumstance where the versioning check will fail and that's: [after a pull request has been merged and before the "Update PolicyEngine US" commit has been automatically pushed]. But this should almost never happen.

So basically: no, you're fine in pretty much all cases (though I'd say it's good practice to periodically `git pull origin master` and `git push origin BRANCHNAME`, because this helps ensure the testing actions are being run on the most updated version of 'repo if PR was merged').

I think `git pull origin master`. But it depends on your local setup, which I'm guessing. `git pull [remote] [branch]` points to a remote Git repository, and you can see which remote is which by running `git remote get-url origin`, which should point to this repo.

**Comment by martinholmer** [comment]
@nikhilwoodruff,  Thanks for the mini git tutorial.  Very helpful.

**Comment by martinholmer** [comment]
@MaxGhenis,  Hasn't issue #1495 been resolved?
