### ISSUE TITLE
Set SSI aged-blind-disabled to current receipt > 0

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-us#1614]

**Comment by MaxGhenis** [comment]
As some background, 2021 SSI totals:
* [$61 billion per SSA](https://www.ssa.gov/budget/FY22Files/2022SSI.pdf#page=5) (estimated $68 billion in 2022)
* $50 billion reported in the CPS ([notebook](https://colab.research.google.com/drive/1TZwoJhw58zxCHImUlLAA4K4hpN0iPk4k?usp=sharing))
* $63 billion in SSI in the CPS based on our computations (same notebook)

The $50 billion reported in the CPS also likely includes state supplements, so our computations bring the federal SSI total much closer to reality. However, our accuracy likely breaks down poorly across demographic groups, since:
* We only capture SSI among the aged; we don't use any disability flags
* We don't capture asset tests
* We don't model take-up

All together, we overestimate SSI among the aged population and underestimate it among the blind and disabled. Adopting real SSI take-up will result in us failing to capture newly eligible people (due to income limit changes), but will more accurately capture SSI's current impact, until we properly model the above components.
