### ISSUE TITLE
Rename "social security" variable

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1796]
PolicyEngineUS focuses on US federal and state taxes and benefits.  The largest benefit is not simulated but figures in the determination of federal and state income taxes.  That benefits is, in the current code, called "social_security".  But that is an imprecise slang expression for benefits paid by the Old-Age, Survivors, and Disability Insurance (OASDI) program that is administered by the federal Social Security Administration (SSA).

PolicyEngineUS avoids slang when describing other benefits programs.  For example, it uses `snap` instead of food_stamps.

The code would be more succinct, and more consistent with the naming of other benefits, if it used `oasdi` instead of the current `social_security`.

**Comment by martinholmer** [comment]
It makes sense to rename the `social_security` variable to `oasdi` in the same pull request that does the variable renaming discussed in issue #1793.  @MaxGhenis, do you approve?   If so, I can develop the pull request.

**Comment by nikhilwoodruff** [comment]
I think on balance this is persuasive. But if it could cause confusion I'd favour at least including social security in the label or documentation (e.g. "OASDI (social security)")

**Comment by martinholmer** [comment]
@nikhilwoodruff said in issue #1796:
> I think on balance this is persuasive.  But if it could cause confusion I'd favour at least including social security in the label or documentation (e.g. "OASDI (social security)").

That makes sense.   But I'm curious why there is no slang ("food stamps") in the `snap` variable metadata:

<img width="1663" alt="Screenshot 2023-02-17 at 9 13 37 AM" src="https://user-images.githubusercontent.com/12170745/219679017-120d7630-a673-4204-b143-6438494f50b6.png">

Why would there be confusion about `oasdi` if there would not be confusion about `snap`?

**Comment by MaxGhenis** [comment]
I don't view these as equivalent. The `food stamp` term is no longer in use; the [SNAP website](https://www.fns.usda.gov/snap/supplemental-nutrition-assistance-program) doesn't mention it. Social Security is the name of the agency that administers OASDI, laypeople never use the OASDI term, SSDI is the standard acronym for that program, and tax and benefit rules generally refer to `Social Security benefits` rather than `OASDI` when defining relevant income concepts.

`social_security` also provides consistency with per-program variables `social_security_{retirement,disability,survivor}_benefits`.

Could the current variable name `social_security` be misconstrued as including programs other than OASDI, or not including all of OASDI?
