### ISSUE TITLE
Error when computing co_chp_out_of_pocket_maximum via back end

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-us#3153]
While repairing some back-end tests, whenever I attempt to calculate a household under a policy, I receive something akin to the following error message:

`Error computing co_chp_out_of_pocket_maximum for your first dependent: The parameter 'gov.states.co.hcpf.chp[out_of_pocket]' was not found in the 2023-01-01 tax and benefit system.`

Could this be an issue in PolicyEngine-Core? Perhaps some sort of minor variable reference issue?

**Comment by martinholmer** [comment]
@anth-volk said in issue #3153:
> I receive something akin to the following error message:
>```
> Error computing co_chp_out_of_pocket_maximum for your first
> dependent:
> The parameter 'gov.states.co.hcpf.chp[out_of_pocket]' was not found
> in the 2023-01-01 tax and benefit system.
>```

Just a guess: perhaps because that parameter is defined beginning in `2023-04-1`?

Here's a screenshot of the parameter file:

<img width="1481" alt="Screenshot 2023-10-15 at 10 41 50 AM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/abe6bd20-d952-465f-90ee-fd048691e393">

**Comment by MaxGhenis** [comment]
Yes that's right @martinholmer. @CalebPena also had an issue with this Colorado CHP+ variables for this reason. Filed https://github.com/PolicyEngine/policyengine-us/issues/3156 to backdate the rules.

**Comment by anth-volk** [comment]
I knew I had seen this variable come up elsewhere! Apologies for the duplicate.
