### ISSUE TITLE
Couples SSI Amount If Eligible

### ISSUE THREAD

**Issue by CalebPena** [PolicyEngine/policyengine-us#3744]
@nikhilwoodruff Is it a bug that `ssi_amount_if_eligible` will return the couples limit for both members if both members are eligible. If it is not a bug, then I think that `tax_unit_ssi` has a bug because it will add the couples `ssi` value twice.

**Comment by nikhilwoodruff** [comment]
Hey- so I don't think so because `tax_unit_ssi` sums `ssi` which sums `uncapped_ssi` which multiplies the amount by `is_ssi_eligible_individual` (and explicitly disallows it for the spouse). If the claim is joint, one member will be the eligible individual (with the joint claim being true) and one will be the spouse.
