### ISSUE TITLE
Fix New Jersey property tax credit income eligibility logic

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#4475]
A number of bugs introduced in PR #4461 have caused a massive regression in NJ income tax testing results.  Income eligibility for the NJ property tax credit is based on NJ gross income (not federal AGI as misspecified in PR #4461).   Here are examples of the recently introduced bugs in the NJ income tax code:

https://github.com/PolicyEngine/policyengine-us/blob/e3edf3fe1f3597fc2103c1a00571e4962d6e37c1/policyengine_us/variables/gov/states/nj/tax/income/credits/property_tax_credit/nj_property_tax_credit_eligible.py#L40-L42

https://github.com/PolicyEngine/policyengine-us/blob/e3edf3fe1f3597fc2103c1a00571e4962d6e37c1/policyengine_us/parameters/gov/states/nj/tax/income/credits/property_tax/income_limit.yaml#L1

**Comment by MaxGhenis** [comment]
Thanks Martin. @hua7450 in the future could you please file a separate issue before adjusting an existing program? #4461 went beyond the title and description by amending the property tax credit in 2021.

@martinholmer, could you share why the lack of the NJ property tax credit income limit prior to #4461 didn't result in validation failures for 2021? Was it not in taxsim, or is it too niche a case to show up? If the latter could you add filers to the validation set that would be affected?

**Comment by hua7450** [comment]
I apologize, I will use more accurate descriptions for PRs in the future.

**Comment by martinholmer** [comment]
@MaxGhenis asked in issue #4475:

> [@martinholmer](https://github.com/martinholmer), could you share why the lack of the NJ property tax credit income limit prior to [#4461](https://github.com/PolicyEngine/policyengine-us/pull/4461) didn't result in validation failures for 2021? 

I don't know.  Are you really sure there was no income limit in the older code?

> Was it not in taxsim?

It has always been in TAXSIM35, which is why we used to not get property tax credit diffs.

> or is it too niche a case to show up? 

The samples being used today are exactly the same as the samples we've been using over the past year or more.   So, the cases in which this difference showed up after PR #4461 have always been in the samples.

> If the latter could you add filers to the validation set that would be affected?

This is not necessary because we have test failures in the standard samples (for example, property tax diffs in 134 cases in the `q21` sample of 100,000 cases).

**Comment by MaxGhenis** [comment]
>Are you really sure there was no income limit in the older code?

I think this requires more digging, and a legal code reference. `nj_property_tax_credit_eligible` is based in part on `nj_property_tax_deduction_eligible`, which has an income limit. But the credit has other eligibility options that did not consider income prior to #4461; see [these lines](https://github.com/PolicyEngine/policyengine-us/pull/4461/files#diff-05fedcfb82d840632e4c17c30b476fd0b1ec8c9ac92d7944e3d52000851d8338R40-R42):

<img width="745" alt="image" src="https://github.com/PolicyEngine/policyengine-us/assets/6076111/91917f50-d697-4743-8f40-9cec469df95a">

[Here](https://github.com/PolicyEngine/policyengine-us/blob/acda3bb89b9423fe5170c14258b7ecf3b583b4a4/policyengine_us/variables/gov/states/nj/tax/income/property_tax/nj_property_tax_credit_eligible.py) you can see the file at its previous snapshot.

At first glance it's not obvious how these interact. Maybe @leogoldman remembers?

**Comment by leogoldman** [comment]
I think you have it right, Max. The income limit applies in all cases to the NJ Property Tax _Deduction_ (appropriate `nj_agi` check in `nj_property_tax_deduction_eligible`). Property tax paying filers that are seniors, blind, or disabled that do NOT meet the income limit are still eligible for the NJ Property Tax _Credit_, which is why we had `nj_property_tax_credit_eligible` set to either `nj_property_tax_deduction_eligible` OR (Pays property taxes AND blind/disabled), with no check on income for the latter group.

#4461 introduces an AGI check for these filers.

From [page 25 (pdf page 27) of the 2023 NJ-1040 instructions](https://www.nj.gov/treasury/taxation/pdf/current/1040i.pdf#page=27):
> Seniors or Blind/Disabled Persons Not Required to File
Form NJ-1040
If you (or your spouse if filing jointly) were 65 or older or blind
or disabled on the last day of the tax year, and your income on
line 29 is $20,000 or less ($10,000 if filing status is single or
married/CU partner, filing separate return), and you met the eligibility requirements, you qualify for a Property Tax Credit.
If you are eligible for a Property Tax Credit, you can
claim your credit on Form NJ-1040 or you can file Form
NJ-1040-HW only (see page 49). Do not file both Form
NJ-1040 and Form NJ-1040-HW.
