### ISSUE TITLE
Add hours response in labor supply

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-us#4518]
Assigning proportional hours changes as labor supply changes.

**Comment by MaxGhenis** [comment]
I'd suggest we use `HRSWK * WKSWORK`.

From the [2023 ASEC codebook](https://www2.census.gov/programs-surveys/cps/datasets/2023/march/asec2023_ddl_pub_full.pdf):
* `HRSWK`: "In the weeks that ... worked how may hours did ... usually work per week?"
* `WKSWORK`: "During 20.. in how many weeks did ... work even for a few hours? (include paid vacation and sick leave as work.)"

Other variables seem to concern a single job and/or the survey week rather than the prior calendar year.
