### ISSUE TITLE
Add the CARES act charity deduction provision for non-itemizers

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#4827]
PolicyEngine-US 1.35.0 does not implement the 2020-2021 CARES provision that allowed non-itemizers to claim some charity contributions as a deduction in addition to their standard deduction.

See this [IRS document](https://www.irs.gov/newsroom/expanded-tax-benefits-help-individuals-and-businesses-give-to-charity-during-2021-deductions-up-to-600-available-for-cash-donations-by-non-itemizers) about this provision's extension through 2021.

**Comment by Mshuning** [comment]
@PavelMakarchuk Is there any existing eligible file related to `charitable_deduction`?

**Comment by Mshuning** [comment]
> > @PavelMakarchuk Is there any existing eligible file related to `charitable_deduction`?
> 
> No there is not,

Should I create it for this issue?

**Comment by PavelMakarchuk** [comment]
> > > @PavelMakarchuk Is there any existing eligible file related to `charitable_deduction`?
> > 
> > 
> > No there is not,
> 
> Should I create it for this issue?

No, we should not check for eligibility here

**Comment by PavelMakarchuk** [comment]
I think the easiest way to do this is to:
New file `charitable_deduction_for_non_itemizers`
New parameter file in `policyengine_us/parameters/gov/irs/deductions/itemized/charity` `non_itemizers_amount.yaml`
Adjust the `charitable_deduction` so there are two variable files - one for the amount that can be attributed to non itemizers and one for the remaining deduction amount 

Amount: 600 (300 for singles) in 2020 and 0 in all other years 

Change the formula in `taxable_income_deductions` so that in 2020 the amount of `charitable_deduction` for non itemizers is included irregardless of the itemization choice
