### ISSUE TITLE
Additional Empire State Child Credit

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#4836]
https://www.tax.ny.gov/pit/empire-child-credit-payments.htm

**Comment by PavelMakarchuk** [comment]
@martinholmer does TAXSIM account for the additional empire state tax credit in 2021?

I am adding the code to PE and it seems like I am failing the integration test Tax unit with taxsimid 92522 in e21.its.csv and e21.ots.csv due to the newly added supplemental credit in 2021 

This leads me to assume that TAXSIM might have no added the supplemental Empire State 

@MaxGhenis do you know whether it was paid out in 2021? I cant seem to find more resources but it is in the law:

[Law](https://www.nysenate.gov/legislation/laws/TAX/606)
2021:
![image](https://github.com/user-attachments/assets/2064834a-abc2-438b-a4a5-3ee3ebf65b4b)
2023:
![image](https://github.com/user-attachments/assets/7a03eb59-8480-40b1-9ab2-fd09ab53f7f7)

**Comment by PavelMakarchuk** [comment]
> @martinholmer does TAXSIM account for the additional empire state tax credit in 2021?
> 
> I am adding the code to PE and it seems like I am failing the integration test Tax unit with taxsimid 92522 in e21.its.csv and e21.ots.csv due to the newly added supplemental credit in 2021
> 
> This leads me to assume that TAXSIM might have no added the supplemental Empire State
> 
> @MaxGhenis do you know whether it was paid out in 2021? I cant seem to find more resources but it is in the law:
> 
> [Law](https://www.nysenate.gov/legislation/laws/TAX/606) 2021: ![image](https://private-user-images.githubusercontent.com/110687043/355607119-2064834a-abc2-438b-a4a5-3ee3ebf65b4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5ODEzNTcsIm5iZiI6MTcyMjk4MTA1NywicGF0aCI6Ii8xMTA2ODcwNDMvMzU1NjA3MTE5LTIwNjQ4MzRhLWFiYzItNDM4Yi1hNGE1LTNlZTNlYmY2NWI0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQyMTUwNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjc4NGQyMDI0NTY5ZjBjOTViN2FmZTlmMDZkNWZlYzhiOTNmMzk3MjBmMjEzMTZhNGViMzllM2ZmYmVkZmJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uV3wmMsWY1dixvUWEqsmw3UNtV-oDJwASTePpxepC8g) 2023: ![image](https://private-user-images.githubusercontent.com/110687043/355608413-7a03eb59-8480-40b1-9ab2-fd09ab53f7f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5ODEzNTcsIm5iZiI6MTcyMjk4MTA1NywicGF0aCI6Ii8xMTA2ODcwNDMvMzU1NjA4NDEzLTdhMDNlYjU5LTg0ODAtNDBiMS05YWIyLWZkMDlhYjUzZjdmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQyMTUwNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODJlY2RkODcyYWY4NmY5YmRlNDdjZThjY2JjMjFkNmNkMTEzODVlNmQ1NzViYTZkZmRmMmVhYWNjYmIwOTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._E4HzEwFSZCHUDB537YGj1D_ejDYGhQSCnTvUN_xaZ4)

PR test for reference:
https://github.com/PolicyEngine/policyengine-us/actions/runs/10274434333/job/28431143088?pr=4843

**Comment by martinholmer** [comment]
@PavelMakarchuk asked in issue #4836:
 > @martinholmer does TAXSIM account for the additional empire state [child] tax credit in 2021?

I don't know.  We didn't get that far before the state income tax testing program was terminated.
