### ISSUE TITLE
Delete `data` folder and replace with proper structure necessary to download, not build, datasets

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#5078]
This should now all be `policyengine-us-data`

**Comment by anth-volk** [comment]
Because of changes to remove heavier dependencies, this now causes API updates ([link](https://github.com/PolicyEngine/policyengine-api/actions/runs/10902861343/job/30255693028)) and US package updates ([link](https://github.com/PolicyEngine/policyengine-us/actions/runs/10902763318/job/30255380873)) to fail.
